#!/usr/bin/env python3
"""
Norfolk AI Labs - Content Publishing Script
Publishes HTML artifacts to share.norfolkailabs.com
"""

import os
import sys
import argparse
import shutil
import json
import subprocess
import tempfile
from datetime import datetime
from pathlib import Path
import re

# Configuration
REPO_ROOT = Path(__file__).parent.parent
PUBLIC_DIR = REPO_ROOT / "public"
ASSETS_DIR = PUBLIC_DIR / "assets"

def validate_slug(slug):
    """Validate and sanitize slug for URL safety"""
    # Remove special characters, convert to lowercase, replace spaces with hyphens
    slug = re.sub(r'[^a-zA-Z0-9\s\-_]', '', slug)
    slug = re.sub(r'\s+', '-', slug.strip().lower())
    slug = re.sub(r'-+', '-', slug)  # Remove multiple consecutive hyphens
    slug = slug.strip('-')  # Remove leading/trailing hyphens
    
    if not slug or len(slug) < 1:
        raise ValueError("Slug cannot be empty after sanitization")
    
    if len(slug) > 50:
        raise ValueError("Slug too long (max 50 characters)")
    
    # Check for reserved names
    reserved = {'assets', 'index', 'admin', 'api', 'www'}
    if slug in reserved:
        raise ValueError(f"Slug '{slug}' is reserved")
    
    return slug

def extract_title_from_html(html_content):
    """Extract title from HTML content"""
    import re
    
    # Try to find title tag first
    title_match = re.search(r'<title[^>]*>([^<]+)</title>', html_content, re.IGNORECASE)
    if title_match:
        return title_match.group(1).strip()
    
    # Try to find first h1
    h1_match = re.search(r'<h1[^>]*>([^<]+)</h1>', html_content, re.IGNORECASE)
    if h1_match:
        return h1_match.group(1).strip()
    
    return "Untitled"

def inject_branding(html_content, title, slug):
    """Inject Norfolk AI branding into HTML content"""
    
    # Check if already has Norfolk branding
    if 'norfolk-header' in html_content or 'Norfolk AI Labs' in html_content:
        print(f"  Content already has Norfolk branding, using as-is")
        return html_content
    
    # Simple branding injection - wrap content in Norfolk template
    branded_html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title} | Norfolk AI Labs</title>
    <meta name="description" content="{title} - Norfolk AI Labs">
    <link rel="stylesheet" href="/assets/style.css">
</head>
<body>
    <header class="norfolk-header">
        <h1>Norfolk AI Labs</h1>
        <div class="subtitle"><a href="/" style="color: white; text-decoration: none;">Shared Content</a> → {title}</div>
    </header>

    <main class="norfolk-content">
        {html_content}
    </main>

    <footer class="norfolk-footer">
        <p>© 2026 Norfolk AI Labs • Generated by <a href="https://github.com/openclaw/openclaw">Atlas</a> • <a href="https://github.com/norfolkailabs/share-pages">Source</a></p>
    </footer>
</body>
</html>"""
    
    return branded_html

def update_index(slug, title, description="", tags=None):
    """Update the homepage index with new content"""
    index_path = PUBLIC_DIR / "index.html"
    
    if not index_path.exists():
        raise FileNotFoundError("Index file not found")
    
    # Read current index
    with open(index_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Create new page item HTML
    tags_html = ""
    if tags:
        tags_html = "\n                <div class=\"page-tags\">\n"
        for tag in tags:
            tags_html += f"                    <span class=\"tag\">{tag}</span>\n"
        tags_html += "                </div>"
    
    new_item = f"""            <li class="page-item">
                <h3 class="page-title">
                    <a href="/{slug}/">{title}</a>
                </h3>
                <div class="page-meta">
                    Published: {datetime.now().strftime('%B %d, %Y')} • Generated by Atlas
                </div>
                <div class="page-description">
                    {description}
                </div>{tags_html}
            </li>"""
    
    # Find insertion point (after existing items, before closing </ul>)
    if f'href="/{slug}/"' in content:
        print(f"  Content with slug '{slug}' already exists in index, skipping update")
        return
    
    # Insert new item at the beginning of the list (after opening <ul>)
    ul_start = content.find('<ul class="page-list">')
    if ul_start == -1:
        raise ValueError("Could not find page list in index")
    
    insertion_point = content.find('\n', ul_start) + 1
    new_content = content[:insertion_point] + new_item + '\n' + content[insertion_point:]
    
    # Write updated index atomically
    with tempfile.NamedTemporaryFile(mode='w', encoding='utf-8', delete=False, dir=PUBLIC_DIR.parent) as tmp:
        tmp.write(new_content)
        tmp_path = tmp.name
    
    try:
        shutil.move(tmp_path, index_path)
        print(f"  Updated index with new content")
    except Exception as e:
        os.unlink(tmp_path)
        raise e

def git_commit_and_push(slug, title):
    """Commit changes and push to GitHub"""
    try:
        # Add all changes
        subprocess.run(['git', 'add', '.'], cwd=REPO_ROOT, check=True, capture_output=True)
        
        # Commit with meaningful message
        commit_msg = f"Add: {title} ({slug})"
        subprocess.run(['git', 'commit', '-m', commit_msg], cwd=REPO_ROOT, check=True, capture_output=True)
        
        # Push to origin
        result = subprocess.run(['git', 'push', 'origin', 'main'], cwd=REPO_ROOT, check=True, capture_output=True, text=True)
        print(f"  Git push successful")
        return True
        
    except subprocess.CalledProcessError as e:
        print(f"  Git operation failed: {e}")
        if e.stderr:
            print(f"  Error: {e.stderr}")
        return False

def main():
    parser = argparse.ArgumentParser(description='Publish HTML content to Norfolk AI Labs share site')
    parser.add_argument('html_file', help='HTML file to publish')
    parser.add_argument('--slug', required=True, help='URL slug for the content')
    parser.add_argument('--title', help='Title for the content (auto-detected if not provided)')
    parser.add_argument('--description', default='', help='Description for the content')
    parser.add_argument('--tags', help='Comma-separated tags')
    parser.add_argument('--no-push', action='store_true', help='Skip git push (for testing)')
    
    args = parser.parse_args()
    
    # Validate inputs
    html_file = Path(args.html_file)
    if not html_file.exists():
        print(f"Error: HTML file '{html_file}' not found")
        return 1
    
    try:
        slug = validate_slug(args.slug)
    except ValueError as e:
        print(f"Error: {e}")
        return 1
    
    # Check if slug already exists
    target_dir = PUBLIC_DIR / slug
    if target_dir.exists():
        print(f"Warning: Content with slug '{slug}' already exists. Overwriting...")
    
    # Read HTML content
    try:
        with open(html_file, 'r', encoding='utf-8') as f:
            html_content = f.read()
    except Exception as e:
        print(f"Error reading HTML file: {e}")
        return 1
    
    # Extract or use provided title
    title = args.title or extract_title_from_html(html_content)
    print(f"Publishing: {title}")
    print(f"  Slug: {slug}")
    print(f"  Target: /{slug}/")
    
    # Process tags
    tags = []
    if args.tags:
        tags = [tag.strip() for tag in args.tags.split(',') if tag.strip()]
    
    try:
        # Create target directory
        target_dir.mkdir(parents=True, exist_ok=True)
        
        # Inject branding
        print(f"  Injecting Norfolk AI branding...")
        branded_content = inject_branding(html_content, title, slug)
        
        # Write content
        target_file = target_dir / "index.html"
        with open(target_file, 'w', encoding='utf-8') as f:
            f.write(branded_content)
        print(f"  Content written to {target_file}")
        
        # Update index
        print(f"  Updating homepage index...")
        update_index(slug, title, args.description, tags)
        
        # Git operations
        if not args.no_push:
            print(f"  Committing and pushing to GitHub...")
            if git_commit_and_push(slug, title):
                print(f"✅ Published successfully!")
                print(f"   URL: https://share.norfolkailabs.com/{slug}/")
                print(f"   Note: Cloudflare Pages deployment may take 1-2 minutes")
            else:
                print(f"❌ Git push failed - content created locally but not deployed")
                return 1
        else:
            print(f"✅ Content created locally (skipped git push)")
            print(f"   Local path: {target_file}")
        
        return 0
        
    except Exception as e:
        print(f"❌ Publishing failed: {e}")
        return 1

if __name__ == '__main__':
    sys.exit(main())